### ISSUE TITLE
Expose unicode::PERLW

### ISSUE THREAD

**Issue by jneem** [rust-lang-nursery/regex#119]
In order to actually turn the output of regex_syntax into an automaton, you need to know what characters count as word characters (for WordBoundary and NotWordBoundary). As far as I can tell, this is the only thing you need from `mod unicode`, since all the other character classes are turned into CharClass already.

**Comment by BurntSushi** [comment]
I really don't want to expose that. My hope was that word boundaries might not be defined in this crate at all, although perhaps that is wishful thinking.

In any case, the actual `regex` crate uses [`is_word_char`](https://github.com/rust-lang/regex/blob/master/regex-syntax/src/lib.rs#L949-L964) from `regex-syntax`, which is unfortunately exposed but undocumented. I think I'd be OK marking that public.

**Comment by jneem** [comment]
Yes, I saw `is_word_char`, but it would be much more convenient to have a more explicit representation of the allowed characters -- in [`regex_dfa`](https://github.com/jneem/regex-dfa), I'm representing all sets of chars with the `CharSet` struct (basically similar to `CharClass` in `regex_syntax`), and if I can't get the same representation for word characters then I'd have to do a special case.

> My hope was that word boundaries might not be defined in this crate at all, although perhaps that is wishful thinking.

Out of curiosity, what did you mean by this? Are you suggesting not supporting word boundaries in the regex syntax? Or did you just mean that Expr would represent them in a less specialized way?

**Comment by BurntSushi** [comment]
> Out of curiosity, what did you mean by this? Are you suggesting not supporting word boundaries in the regex syntax? Or did you just mean that Expr would represent them in a less specialized way?

The definition of "word boundary" in `regex-syntax` is just the Unicode definition. My hope was that some other crate could provide an implementation of that definition. Similarly for case folding. However, at least, the case folding code has become rather specialized, so perhaps that won't happen.

I think I am just not convinced *either* way here, which I think means we should be conservative. I think my recommendation for now would be to just copy `PERLW` into your crate. The duplication is unfortunate, but on its own, it is not that big and it at least resolves your immediate issue.

**Comment by jneem** [comment]
Ah, I get it. In the long run, I guess it makes sense for this to be in some other create. But for now, I'll just copy it.

**Comment by BurntSushi** [comment]
I'm going to close this. I think copying is a fine solution for now.
