### ISSUE TITLE
Please tag releases

### ISSUE THREAD

**Issue by anguslees** [rust-lang-nursery/regex#123]
Releases are pushed to crates.io, without (afaics?) a corresponding git tag or github release - making it hard to match git source revision with cargo versions.  It would be neat if there was some git artifact of each push to crates.io.

**Comment by huonw** [comment]
This should apply to all rust-lang & rust-lang-nursery crates.

**Comment by BurntSushi** [comment]
OK, I have a shell script for combined version bumping/publishing/git pushing that I'll use from now on.

@huonw We should probably try to settle on conventions---or even a tool---to use to do this for us. e.g., This repo alone is home to three crates, so it should have three distinct tagging schemes...
