### ISSUE TITLE
Allow accessing meta info for capture groups

### ISSUE THREAD

**Issue by flying-sheep** [rust-lang-nursery/regex#125]
When using user-supplied regexes, I need information about the only dynamic property of those regexes: the number and names of capture groups.

This is useful to allow users to e.g. specify a subset of possible groups.

**Comment by BurntSushi** [comment]
That seems reasonable. Other regex libraries support this IIRC.

One idea is to simply expose the internal representation, which is a `Vec<Option<String>>`. The length of that vec is the number of capture groups (which is always at least `1`), and the capture group at index `i` has `Some("name")` if it was given a name in the regex. The capture group at index `0` is always unnamed.

**Comment by flying-sheep** [comment]
> One idea is to simply expose the internal representation, which is a `Vec<Option<String>>`.

yeah, that is one option i thought about, the other one being those two functions (their names are to be improved):

```rust
fn ncaptures(&self) -> usize;
fn capture_indices(&self) -> HashMap<String, usize>;
```

this would have the advantage of easy checking if an expected name exists or iterating named groups.

we’d also have to think about `ncaptures` counting “capture group 0” or not.

**Comment by BurntSushi** [comment]
I'd be hesitant to create a hash map here. Seems a bit heavy handed.

We could instead expose `&self.capture_names[1..]`, which would be a `&[Option<String>]` but would not expose the first capture group (which is pretty pointless). On the other hand, that means that a capture group indexed by `1` in the regex (and in the `Captures` type) is now at index `0` in the `&[Option<String>]`. That seems bad.

**Comment by flying-sheep** [comment]
yeah, if we use a vector, the group indices should correspond to the vector indices.

else off-by-one errors would abound.

and sure, rust has enough functional tools to quickly get what people want out of the tool, e.g. sth. like:

```rust
let mut a = None;
let mut b = None;
for i, opt_name in re.capture_names().iter().enumerate() {
	match opt_name {
		Some("a") => { a = i },
		Some("b") => { b = i },
		None => {},
	}
}
```

**Comment by BurntSushi** [comment]
It's also easy enough to create your own hash map if you need that too: http://is.gd/NqtAWN

**Comment by flying-sheep** [comment]
sure, and i’m not against just using the vector.

i’m just thinking if the cost of creating the hashmap isn’t justified because the API is better.

`Vec<Option<String>>` just seems unwieldy if everything you’d ever do with it is looking for known names or looping existing name/index pairs.

so the questions are:

1. what use cases are there that can be served by the vector better than by the hash map
2. are there use cases that need amazing performace when accessing this information.

i i think the answers are probably “no” and “no” :smile:

**Comment by BurntSushi** [comment]
@flying-sheep The modus operandi in Rust is to not make choices that impose unavoidable costs on the caller when possible. Returning `&[Option<String>]` is free, which is pretty compelling IMO.

Happy to hear more thoughts though!

**Comment by flying-sheep** [comment]
yeah, well, maybe the time i spent to make [above example work](https://play.rust-lang.org/?code=use%20std%3A%3Acollections%3A%3AHashMap%3B%0A%0Afn%20main%28%29%20{%0A%20%20%20%20let%20caps%20%3D%20vec![%0A%20%20%20%20%20%20%20%20None%2C%0A%20%20%20%20%20%20%20%20Some%28%22foo%22.to_owned%28%29%29%2C%0A%20%20%20%20%20%20%20%20None%2C%0A%20%20%20%20%20%20%20%20Some%28%22bar%22.to_owned%28%29%29%2C%0A%20%20%20%20%20%20%20%20Some%28%22baz%22.to_owned%28%29%29%2C%0A%20%20%20%20]%3B%0A%20%20%20%20let%20map%3A%20HashMap%3CString%2C%20usize%3E%20%3D%0A%20%20%20%20%20%20%20%20caps.iter%28%29%0A%20%20%20%20%20%20%20%20%20%20%20%20.enumerate%28%29%0A%20%20%20%20%20%20%20%20%20%20%20%20.filter_map%28|%28i%2C%20name%29|%20name.as_ref%28%29.map%28|name|%20%28name.clone%28%29%2C%20i%29%29%29%0A%20%20%20%20%20%20%20%20%20%20%20%20.collect%28%29%3B%0A%20%20%20%20println!%28%22{%3A%3F}%22%2C%20map%29%3B%0A}&version=stable)

**Comment by flying-sheep** [comment]
but as said: i’m not against the vector i just think it’s pretty ugly when compared to alternate APIs.

**Comment by flying-sheep** [comment]
hmm, yeah, you’re right. no cost and it’s relatively easy to get a better data structure from it.

**Comment by flying-sheep** [comment]
ok, about implementation:

* `ExNative` has `names: &'static &'static [Option<&'static str>]`
* `Program` has `cap_names: Vec<Option<String>>`

we can’t do this, right?

```rust
pub fn capture_names(&self) -> &[Option<&str>] {
    use Regex::*;
    match *self {
        Dynamic(prog) => prog.cap_names.iter().map(|&o| o.as_ref()).collect(),
        Native(nat) => *nat.names,
    }
}
```

so wat do? i’m too new for this :smile:

**Comment by flying-sheep** [comment]
#rust suggests returning an iterator, which basically would mean that we just remove `#[doc(hidden)]` from `names_iter` and call it a day.
