### ISSUE TITLE
bug in captures

### ISSUE THREAD

**Issue by BurntSushi** [rust-lang-nursery/regex#129]
```
let re = Regex::new(r"(?P<re>(\d{1,}(\.\d{1,})?\s){3}?re)|(?P<h>((\d{1,}(\.\d{1,})?\s){2}?l\s){3}?h)").unwrap();
let data = r"290.52 720.24 m 321.48 720.24 l 321.48 709.44 l 290.52 709.44 l h";
```

From https://users.rust-lang.org/t/regex-match-issues/3604/2:

> If you change the {3} to a {2} in the re group, you get a partial capture in the h group, and if you change it to {1} (or remove it entirely), you get the full capture.

**Comment by lambda** [comment]
Further minimization:

```rust
let re = Regex::new(r"(?P<a>(\d){2}a)|(?P<b>\d{2}b)").unwrap();
let data = r"12b";
```

This results in `None` for the `b` capture group.

The following results in `Some("12b")`:

```
r"(?P<a>\d{2}a)|(?P<b>\d{2}b)"
r"(?P<a>(\d)+a)|(?P<b>\d{2}b)"
```

The following results in `None`:

```
r"(?P<a>(\d){2}a)|(?P<b>\d+b)"
r"(?P<a>(\d){2,}a)|(?P<b>\d{2}b)"
r"((\d){2}a)|(?P<b>\d{2}b)"
```

It looks like to trigger this you need to have a capture group inside of the first capturing group.

I then tried using numbered capture groups rather than named. Interestingly, you get the right result via a numbered capture group, but not via the named capture group:

```rust
    let re = Regex::new(r"((\d){2}a)|(?P<b>\d+b)").unwrap();
    let data = r"12b";

    for caps in re.captures_iter(data) {
        println!("{:?} {:?} {:?} {:?} {:?}",
                 caps.at(0),
                 caps.at(1),
                 caps.at(2),
                 caps.at(3),
                 caps.name("b"));
    }
```

Gives me:

```
Some("12b") None None Some("12b") None
```

But if I change the `{2}` to a `{1}` I get:

```
Some("12b") None None Some("12b") Some("12b")
```

**Comment by BurntSushi** [comment]
Interesting. This might actually be related to using `{N}` directly proceding a capture group. It might be replicating instructions in a way that also replicates the capture groups. I'll have to look at the compiler to see exactly what it's doing, but it is code I had changed around the time frame quoted in the linked discussion.

@lambda Thanks so much for digging into this more. This is a great bug report. :-)

**Comment by BurntSushi** [comment]
Here is a smaller test case and a regression test:

```rust
#[test]
fn regression_captures_rep() {
    let re = regex!(r"([a-f]){2}(?P<foo>[x-z])");
    let caps = re.captures("abx").unwrap();
    assert_eq!(caps.name("foo").unwrap(), "x");
}
```

The bug here is pretty complex and is a result of an optimization that broke an invariant in the compiler. In particular, the `{2}` in the expression `([a-f]){2}` causes the sub expression `([a-f])` to be compiled twice, which is done by a call to `clone` on a `regex_syntax::Expr`. This includes cloning the capture group *and its presumably unique capture index*. Cloning the capture group causes the index to no longer be unique.

The compiler assumes that every capture group it visits is unique, and unambiguously assumes that its capture name and index refers to its group and no other. Cloning the capture group violates this invariant, because you wind up with two distinct expressions identified by precisely the same capture.

The correct repetition of `([a-f]){2}` should correspond to `[a-f]([a-f])`. We can simulate these semantics (I think) by keeping track of the capture indices we've seen in the compiler. If we've already seen a capture index, then we don't record it in our list of capture groups *but we still insert instructions for the capture group*. This has the effect of compiling down to `([a-f])([a-f])` where the capture groups are correctly aliased. Since matching proceeds left-to-right, the latter group always overrides the former. Doing it this way makes the compiler a little simpler.

I believe these semantics extrapolate correctly to repetitions like `([a-f]){2, 5}`.

**Comment by BurntSushi** [comment]
Thanks again @lambda! You made fixing this a lot easier on me. :-)
