### ISSUE TITLE
Can't build on nightly

### ISSUE THREAD

**Issue by yongqli** [rust-lang-nursery/regex#130]
error: no method named `parse_expr_nopanic` found for type `syntax::parse::parser::Parser<'_>` in the current scope
    /Users/yongqli/.cargo/registry/src/github.com-0a35038f75765ae4/regex_macros-0.1.22/src/lib.rs:531     if let Ok(expr) = parser.parse_expr_nopanic() {

**Comment by BurntSushi** [comment]
What version of nightly are you using? Please show the output of `rustc --version`. Thanks!

**Comment by yongqli** [comment]
% rustc --version
    rustc 1.6.0-nightly (bdfb13518 2015-11-14)

**Comment by BurntSushi** [comment]
This was broken in rust-lang/rust/commit/44d8abcc

**Comment by BurntSushi** [comment]
@yongqli Thanks for the report! This is fixed and uploaded to crates.io in `regex_macros 0.1.23`.
