### ISSUE TITLE
Can't compile on rustc 1.7.0-dev (2016-01-08)

### ISSUE THREAD

**Issue by yongqli** [rust-lang-nursery/regex#147]
regex_macros-0.1.25/src/lib.rs:555:37: 555:41 error: no method named `ok` found for type `bool` in the current scope
    regex_macros-0.1.25/src/lib.rs:555         if !parser.eat(&token::Eof).ok().unwrap() {

**Comment by BurntSushi** [comment]
I'm not sure why, but multirust seems to be stuck on the `2016-01-04` nightly, so it's not easy for me to reproduce and fix. I don't have time to dig further right now.
