### ISSUE TITLE
No documentation for re.replace_all(content, |caps: &Captures| { }) ?

### ISSUE THREAD

**Issue by sck** [rust-lang-nursery/regex#154]
I noticed that there is no documentation for using replace_all with a closure.  This may be related to a bug in rustdoc: https://github.com/rust-lang/rust/issues/29503

**Comment by BurntSushi** [comment]
Could you explain more about what you're looking for? `replace_all` says "See the documentation for replace for details on how to access submatches in the replacement string." The documentation for `replace` has an example using a closure with captures.

**Comment by sck** [comment]
Which documentation are you referring to?  I cannot find any documentation in http://doc.rust-lang.org/regex/regex/index.html on either replace_all or replace about using a closure.... I was looking for the documentation of the API referenced in this stackoverflow post: http://stackoverflow.com/a/27486413
