### ISSUE TITLE
Implement Debug for Captures

### ISSUE THREAD

**Issue by dhardy** [rust-lang-nursery/regex#160]
src/detail/discover.rs:309:40: 309:44 error: the trait `core::fmt::Debug` is not implemented for the type `regex::re::Captures<'_>` [E0277]
    src/detail/discover.rs:309                 println!("caps: {:?}", caps);
                                                                      ^~~~

Be nice if it was.

**Comment by BurntSushi** [comment]
Yes indeed! This is definitely an oversight.

**Comment by BurntSushi** [comment]
This was done in commit 8d81a547cdd143e266519a9ee4aa5c92fad585aa
