### ISSUE TITLE
RegexSet should be constructable with 1 regex

### ISSUE THREAD

**Issue by BurntSushi** [rust-lang-nursery/regex#189]
It currently requires 2 because I thought, "why would you want to use a regex set with only one regex?" Well, in a more generic context, supporting 1 makes using regex sets more ergonomic.

**Comment by defuz** [comment]
Moreover, I think supporting of zero regex also makes sense because of generalization.

**Comment by BurntSushi** [comment]
@defuz Probably, yeah. Agreed.

**Comment by gsquire** [comment]
I can update this if it hasn't been worked on. Do you want to ultimately remove the length restriction?

**Comment by BurntSushi** [comment]
I haven't started yet, so have at it! Beware that some things may rely on the fact that a regex set only exists when there are 2 or more expressions.

**Comment by BurntSushi** [comment]
Done in commit 31a317eadd7d0270dea4ac90b54f5f560514ed01
