### ISSUE TITLE
expected a value of type `string` for the key `lib.name`

### ISSUE THREAD

**Issue by ProgVal** [rust-lang-nursery/regex#195]
When I run `cargo build` on a project depending on this one, I get this:

```
Unable to get packages from source

Caused by:
  failed to parse manifest at `/home/progval/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-0.1.63/Cargo.toml`

Caused by:
  expected a value of type `string` for the key `lib.name`
```

cargo 0.2.0-nightly (a483581 2015-05-14) (built 2015-05-15)

**Comment by BurntSushi** [comment]
That version of Cargo looks pretty old. @alexcrichton Did Cargo used to require a `name` in the `[lib]` section?

**Comment by alexcrichton** [comment]
Yeah older versions of Cargo required that, wuw that Cargo is old! (Rust 1.0?)

**Comment by BurntSushi** [comment]
Yeah, I don't think this crate even compiles on 1.0 at this point? Probably 1.3 is required.

**Comment by ProgVal** [comment]
Actually, that's Cargo from an old Rust install. I installed a newer Rust recently, and thought it installed a new Cargo as well, and I did not notice it before now
