### ISSUE TITLE
regex-syntax 0.2.5 breaks semver

### ISSUE THREAD

**Issue by DanielKeep** [rust-lang-nursery/regex#207]
0.2.5 includes 9967e07, which removes the public re-export of `is_punct` from `regex-syntax`.  This breaks `regex` versions at least as far back as 0.1.41, which depend on `regex-syntax = "0.2"`.  Due to code movement, I wasn't able to establish a tight upper bound, but `regex` 0.1.56 moves to `regex-syntax` 0.3, which avoids the issue.

**Comment by BurntSushi** [comment]
Hmm, that seems like an oversight on my part. Sorry about that!

What can we do to fix it? If I checkout the latest commit for `regex-syntax 0.2.x` and issue a patch release with `is_punct` exported, will that help?

**Comment by DanielKeep** [comment]
I'm not sure.  I tried to override the version of `regex-syntax`, but Cargo wouldn't let me, so I don't know if that's the *only* breaking change.

I should also mention that I've worked around this by just moving my minimum version of `regex` forward to 0.1.56, which uses `regex-syntax` 0.3, so this isn't actively a problem (for me, anyway).  I mostly reported it so you'd be aware of it.

**Comment by BurntSushi** [comment]
cc @rust-lang-nursery/libs

**Comment by alexcrichton** [comment]
@BurntSushi yeah seems like a fix of the 0.2 series of regex-syntax would work for now, and a bump to 0.3 seems fine to me (as it's an unstable crate anyway).

It should be fine to bump the major version of regex-syntax without a major bump of regex as the semantics didn't change and the APIs aren't exported, right?

**Comment by BurntSushi** [comment]
@alexcrichton regex-syntax is actually already at `0.3`. I think this issue is "some *past* combination of `regex` and `regex-syntax` are incompatible because I messed up" and it just hasn't been noticed. So I think what I'd have to do is something like:

```
git checkout regex-syntax-0.2.5
$EDITOR ... (revert semver incompatible change)
$EDITOR Cargo.toml (bump version to 0.2.6)
cargo publish
```

But this is like, modifying history and seems like bad juju. For example, the change above wouldn't even be recorded in repo history...

**Comment by alexcrichton** [comment]
Oh you could also just create a new tag for `regex-syntax-0.2.6` and just have the extra "backport commit" not be part of master mainstream?

**Comment by BurntSushi** [comment]
OK, I've published a `regex-syntax 0.2.6` with a backport fix that should hopefully resolve this. The actual commit is not on `master` but is instead accessible via the [`regex-syntax-0.2.6` tag](https://github.com/rust-lang-nursery/regex/tree/regex-syntax-0.2.6).

**Comment by DanielKeep** [comment]
I realise this is a pain to have to deal with, so props for fixing it.  :)

**Comment by BurntSushi** [comment]
@DanielKeep Thanks for reporting it! :-)
