### ISSUE TITLE
Leftmost/longest and mixed byte + unicode patterns.

### ISSUE THREAD

**Issue by SeanRBurton** [rust-lang-nursery/regex#237]
Matching Alternate([AnyByte, AnyChar]) against "\u{6f1af}" gives the capture range (0, 1), but the longest matching span is (0, 4).

**Comment by BurntSushi** [comment]
That's correct. This library uses leftmost-first semantics. e.g., matching `(a|ab)` against `ab` will yield `a`.

**Comment by BurntSushi** [comment]
It's documented here: https://doc.rust-lang.org/regex/regex/struct.Regex.html#method.find

**Comment by SeanRBurton** [comment]
Ok, thanks.
