### ISSUE TITLE
Iterate captures always with a name

### ISSUE THREAD

**Issue by Keats** [rust-lang-nursery/regex#243]
Not sure if it's a common usecase but i'd like to do something like

```rust
let mut params = HashMap::new();
// bad name
for cap in caps.iter_named_all() {
    match cap.0 {
        Some(name) => {
           params.insert(cap.0.to_string(), cap.1.unwrap().to_string());
        },
        None => {
           // make up a name for it, like unnamed1
           params.insert(made_up_name, cap.1.unwrap().to_string());
    }
}
```
My usecase is a URL router where users might or might not use named captures and a hashmap is nicer to use than a Vec if you are using named ones

**Comment by BurntSushi** [comment]
@Keats I'm having a difficult time understanding the request. It sounds like you should be able to use `captures_iter` to iterate over all non-overlapping successive matches in some text, which will give you a `Captures` for each match. If you have a `Captures`, then you can look up a particular named capturing group using the [`name`](http://doc.rust-lang.org/regex/regex/struct.Captures.html#method.name) method. A `Captures` also provides [`iter_named`](http://doc.rust-lang.org/regex/regex/struct.Captures.html#method.iter_named), which iterates over all capturing groups in a `Captures`.

> My usecase is a URL router

You might consider using a [`RegexSet`](http://doc.rust-lang.org/regex/regex/struct.RegexSet.html) instead, which should provide better performance as the number of routes increases.

**Comment by Keats** [comment]
>You might consider using a RegexSet instead, which should provide better performance as the number of routes increases.
I'm using a RegexSet but want to capture the params as well.

The issue is that the name of the captures are arbitrary, I can have `router.get(r"/(?P<year>\d{4})/(\d{4})", dummy);` for example, that will change for every app.
This regex has one named parameter (`year`) and one not named. To use the `name` method, I need to know the name of the parameter afaik, which I can't know unless I extract them with a regex.

If i use `iter`, I can't get their names (since I don't know them) and using `iter_named` wouldn't return the second capture group according to the docs.

Is that clearer?
It's not a huge deal, I could just only care about named params and disregard unnamed ones

**Comment by BurntSushi** [comment]
@Keats Hmm, yes, I see. That makes sense. I'll see if I can squeeze a solution to it into the `1.0` RFC in my next round of changes.

**Comment by Keats** [comment]
@BurntSushi thanks!

**Comment by BurntSushi** [comment]
@Keats It occurs to me that you could just use the [`Regex::capture_names`](https://doc.rust-lang.org/regex/regex/struct.Regex.html#method.capture_names) method, which gives you an [iterator over all capture names in the regex](https://doc.rust-lang.org/regex/regex/struct.CaptureNames.html). You can use `enumerate` to associate each capture name with an index, if you need it.
