### ISSUE TITLE
Fuzzed regex causes assertion-failure

### ISSUE THREAD

**Issue by lukaslueg** [rust-lang-nursery/regex#250]
AFL found this regex which causes an assertion failure `!ranges.is_empty()` in `regex-0.1.71/src/compile.rs:421` while `Regex::new()` using `rustc-1.11.0-dev 2016-06-13`. In release-mode it causes an `index 18446744073709551615 out of range for slice of length 0`.

```
/=(?-u:\?(?:\[\[:\[\[[^|\]]*(?:\|(?-u:\?[\[[]*(?:\|(?:[^|\]]*))2:[^|\]]*))25[σף]]*(?:\|(?:[^|\]]*)0?:[^|\]]*))25[0])+
```

Beware the special characters. In Base64 it's Lz0oPy11Olw/KD86XFtcWzpcW1xbW158XF1dKig/Olx8KD8tdTpcP1tcW1tdKig/Olx8KD86W158
XF1dKikpMjpbXnxcXV0qKSkyNVvPg9ejXV0qKD86XHwoPzpbXnxcXV0qKTA/OltefFxdXSopKTI1
WzBdKX8r

**Comment by BurntSushi** [comment]
Nice. This is a bug because Unicode literals should be disallowed in character classes when Unicode mode is disabled, but they weren't. A smaller reproducible example is `(?-u)[☃]`.
