### ISSUE TITLE
Endless loop in Regex::captures_iter()

### ISSUE THREAD

**Issue by lukaslueg** [rust-lang-nursery/regex#255]
AFL found this simple regex that causes `Regex::captures_iter()` in `regex-0.1.71` to enter into an endless loop.

```
regex::Regex::new("a$").unwrap().captures_iter("a").last()
```

**Comment by BurntSushi** [comment]
This appears to be an invalid match bug. Namely, this assert fails:

```rust
assert!(Regex::new("a$").unwrap().find_at("a", 1).is_none());
```
