### ISSUE TITLE
Build failure on the latest nightly build

### ISSUE THREAD

**Issue by ujh** [rust-lang-nursery/regex#260]
If I use `regex_macros` on the latest nightly I get the following compiler error:

```
/home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/regex_macros-0.1.37/src/lib.rs:66:55: 66:69 error: type name `ast::TokenTree` is undefined or not in scope [E0412]
/home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/regex_macros-0.1.37/src/lib.rs:66 fn native(cx: &mut ExtCtxt, sp: codemap::Span, tts: &[ast::TokenTree])
```

See also https://travis-ci.org/ujh/iomrascalai/jobs/142258514#L393

**Comment by ujh** [comment]
👍 Thank you.

**Comment by BurntSushi** [comment]
@ujh Out of curiosity, how are you using the `regex_macros` crate? It's quite likely that you'd be better off without it.

**Comment by ujh** [comment]
I just had a look and there are exactly 5 calls to `regex!` in my code. You're right, replacing them with just `Regex::new` is probably not an issue at all.

**Comment by BurntSushi** [comment]
@ujh Don't forget about `lazy_static!`, which is very useful for simulating "global" regexes that are compiled exactly once.

**Comment by ujh** [comment]
Oh, I forgot to mention that it's in a part that is not performance critical at all. But I have other places where lazy_static! would come in handy. 👍
