### ISSUE TITLE
NFA/DFA disagreement with EndText

### ISSUE THREAD

**Issue by SeanRBurton** [rust-lang-nursery/regex#265]
Matching `Alternate([EndText, LiteralBytes { bytes: [118], casei: true }])` against `"v"` gives the match `Some((4, 4))` with the DFA, but `Some((1, 1))` with the NFA. 

Same methodology as #241.

**Comment by BurntSushi** [comment]
I can't reproduce this. This program terminates successfully:

```rust
extern crate regex;

use regex::internal::ExecBuilder;

fn main() {
    let res = r"$|(?i:v)";
    let re0 = regex::Regex::new(&res).unwrap();
    let re1 = ExecBuilder::new(&res).nfa().build().unwrap().into_regex();
    let s = "v";
    assert_eq!(
        re0.find_iter(s).collect::<Vec<_>>(),
        re1.find_iter(s).collect::<Vec<_>>());
}
```

When reporting bugs, could you *please* include code?
