### ISSUE TITLE
Named capture group introspection not exposed by the C API

### ISSUE THREAD

**Issue by davidblewett** [rust-lang-nursery/regex#279]
The C API exposes an iterator over all captures (`rure_iter_next_captures`), and can return the index of a given capture group name (`rure_capture_name_index`). The Rust Regex struct has a `capture_names` iterator, but that doesn't appear to be exposed at the C level.

I don't see a way to retrieve the capture group name while iterating over the set of captures (i.e., given the index of a particular capture give me the corresponding name, hypothetically `rure_capture_index_name`), or to return the list of capture group names (`rure_iter_capture_groups`, for example).

**Comment by BurntSushi** [comment]
Ah yup, it looks like exposing the `capture_names` iterator in some form in the C API should fix this.

**Comment by davidblewett** [comment]
I came upon this while working on Python bindings ( current WIP here: https://github.com/rust-lang-nursery/regex/compare/master...davidblewett:rure-python?expand=1 ). I wanted to implement the `groupdict` method, similar to Python's `re.MatchObject`: https://docs.python.org/2/library/re.html#re.MatchObject.groupdict . 

I'm new to Rust, and have never really used C. I can take a crack at it some time this week.

**Comment by BurntSushi** [comment]
@davidblewett That'd be awesome! I'm not a C expert either but I'd be happy to help mentor you if you'd like. I'm on IRC in the evenings during the week.

**Comment by BurntSushi** [comment]
Fixed in #282
