### ISSUE TITLE
incorrect parsing of regex?

### ISSUE THREAD

**Issue by blaenk** [rust-lang-nursery/regex#280]
I hadn't worked with rust in months so I made major updates of both rustc and my dependencies (including regex). I noticed that my program was now failing in a weird way and I finally tracked it down to this bug (regression?), either that or I'm doing something very wrong here:

``` rust
let re = Regex::new(r"(^\.)|(~$)").unwrap();
assert!(!re.is_match("favicon.png"));
```

That assertion is failing even though it shouldn't AFAIK. It certainly didn't before.

The regex is supposed to match if the string begins with `.` or ends with `~`. Even without the groupings/capture groups it fails. Somehow it is matching on `"favicon.png"`.

I can't imagine something like this got through though so I'm thinking it may be a misunderstanding I have of how that regex should work. I tried this just now in the chrome console with javascript and I don't see this problem there, though I am aware that regex implementations tend to differ, I wasn't aware that they differ in something like this.

**Comment by blaenk** [comment]
[Regulex](https://jex.im/regulex/#!embed=false&flags=&re=(%5E%5C.)%7C(~%24)) seems to confirm my understanding of this pattern, unless I'm misunderstanding the diagram too.

**Comment by BurntSushi** [comment]
Gah. This is probably a bug in the literal optimizer being too aggressive. I'll check it out tomorrow.

**Comment by blaenk** [comment]
No worries, I would appreciate it.

**Comment by BurntSushi** [comment]
@blaenk Interestingly, running `re.find("favicon.png")` returns `None` as it should. The reason why is because the *forward* DFA was falsely reporting a match, but the backward DFA correctly determined it not to match. The `is_match` routine only uses the forward DFA, which resulted in the incorrect match bubbling up.

In any case, the underlying cause was indeed an aggressive literal optimization. #281 should fix it!

**Comment by blaenk** [comment]
Ahhh. Thank you very much for fixing this!

**Comment by blaenk** [comment]
No rush but do you have any idea when a new release will be out on crates.io with this fix? Or is there some set release schedule?

**Comment by BurntSushi** [comment]
It's uploading. :-)

**Comment by blaenk** [comment]
Thank you very much once again!!

**Comment by BurntSushi** [comment]
No problem. `0.1.77` is now on crates.io! Thanks for the bug report!
