### ISSUE TITLE
Redundant TODO Comment

### ISSUE THREAD

**Issue by KodrAus** [rust-lang-nursery/regex#284]
Sorry this is probably the most useless issue ever opened on GitHub, but is this [todo in the `teddy128` mod](https://github.com/rust-lang-nursery/regex/blob/master/src/simd_accel/teddy128.rs#L441) redundant? It looks like it is using Aho-Corasick now.

**Comment by BurntSushi** [comment]
Indeed, it is redundant!

[This comment](https://github.com/rust-lang-nursery/regex/blob/master/src/simd_accel/teddy128.rs#L324-L325) is also wrong. Aho-Corasick is now used in the `slow` loop (but not in the verification step).
