### ISSUE TITLE
Have find() return subslices

### ISSUE THREAD

**Issue by Binero** [rust-lang-nursery/regex#301]
In rust you cannot index a str, so it would be appreciated if find() returns a subslice as opposed to indices of the match.

**Comment by BurntSushi** [comment]
You can absolutely slice a &str. If `s` is a str, then `&s[i..j]` works.

In any case, regex 0.2 changes find to return a `Match`, from which a &str or the offsets can be extracted. Dropping the offsets completely is a non starter.
