### ISSUE TITLE
Question: Backreference possible?

### ISSUE THREAD

**Issue by silvio** [rust-lang-nursery/regex#302]
with perlre it is possible to (back-)reference a capture group. Is this possible with this crate? Iwant to write regex like `r"(.)(.)\2\1"`.

Thanks in advance,
Silvio

**Comment by BurntSushi** [comment]
Nope. The first sentences of the documentation explain why:

> This crate provides a native implementation of regular expressions that is heavily based on RE2 both in syntax and in implementation. Notably, backreferences and arbitrary lookahead/lookbehind assertions are not provided. In return, regular expression searching provided by this package has excellent worst-case performance.

**Comment by silvio** [comment]
Hups! Sorry! ... and thanks

**Comment by JarvisCraft** [comment]
Hi @BurntSushi!

Feels like the link is dead and it would be good to update it given that this issue occurs among the first ones in Google for queries like `rust rg backreference`

**Comment by BurntSushi** [comment]
Fixed, thanks. Note that the answer is still literally in the first paragraph of the crate documentation.

**Comment by JarvisCraft** [comment]
Thanks!

> Note that the answer is still literally in the first paragraph of the crate documentation.

For sure :) It's just a small improve to enhance Google'ability (e.g. I knew this fact, but just wanted to make a quick check)
